# Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
# Oracle Corporation and/or its affiliates. Other names may be trademarks of their respective owners. 

# This sample file, which has been provided by Oracle Corporation as part of an Oracle(r) product for use
# ONLY by licensed users of the product, includes CONFIDENTIAL and PROPRIETARY information of Oracle
# Corporation.

# This material is the confidential property of Oracle Corporation or its licensors and may be used,
# reproduced, stored, or transmitted only in accordance with a valid Oracle license or sublicense
# agreement.

# USE OF THIS SOFTWARE IS GOVERNED BY THE TERMS AND CONDITIONS OF THE LICENSE
# AGREEMENT AND LIMITED WARRANTY FURNISHED WITH THE PRODUCT.

# IN PARTICULAR, YOU WILL INDEMNIFY AND HOLD ORACLE CORPORATION, ITS RELATED COMPANIES AND ITS SUPPLIERS,
# HARMLESS FROM AND AGAINST ANY CLAIMS OR LIABILITIES ARISING OUT OF THE USE, REPRODUCTION, OR DISTRIBUTION
# OF YOUR PROGRAMS, INCLUDING ANY CLAIMS OR LIABILITIES ARISING OUT OF OR RESULTING FROM THE USE,
# MODIFICATION, OR DISTRIBUTION OF PROGRAMS OR FILES CREATED FROM, BASED ON, AND/OR DERIVED FROM THIS
# SAMPLE SOURCE CODE FILE.


# host specific properties

# This is the name of the Web Service module. A deployable war file will be generated with this name (e.g. ReferenceRestUIM.war)
WAR_NAME=ReferenceRestUIM

# Directory under which the war file will be generated
MODULE_NAME=reference_rest_webservice

# WebLogic Server installation directory where server directory is present
WL_HOME=D:\\Oracle\\Middleware\\Oracle_Home\\wlserver

# Weblogic domain directory and UIM home
DOMAIN_HOME=D:\\ANNEM_DOMAIN\\Oracle\\Middleware\\Oracle_Home\\user_projects\\domains
DOMAIN_NAME=annem_domain
UIM_HOME=D:\\ANNEM_DOMAIN\\Oracle\\Middleware\\Oracle_Home\\user_projects\\domains\\annem_domain\\UIM
FMW_HOME=D:\\ANNEM_DOMAIN\\Oracle\\Middleware\\Oracle_Home
APP_LIB=D:\\UIM_SDK_7.8\\UIM_SDK\\lib

# UIM application libraries. Can be obtained from UIM_SDK
UIM_LIB=D:\\UIM_SDK_7.8\\UIM_SDK\\lib

# Location of the UIM custom ear file (or Web services-compatible application archive deploy the Reference WS).
EAR_PATH=D:\\ANNEM_DOMAIN\\Oracle\\Middleware\\Oracle_Home\\user_projects\\domains\\annem_domain\\UIM\\app\\7_8_0\\custom.ear
# Patch class path.
PATCH_CLASSPATH=D:\\Oracle\\Middleware\\Oracle_Home\\wlserver\\server\\lib\\weblogic.jar
